#!/bin/bash

echo "Building Korus App for Android with Native Module Support"
echo "=========================================================="
echo ""
echo "This build includes:"
echo "- Solana Mobile Wallet Adapter (for Seed Vault)"
echo "- Biometric authentication"
echo "- All smart contracts ready for deployment"
echo ""
echo "Please run these commands in order:"
echo ""
echo "1. Login to EAS (if not already logged in):"
echo "   eas login"
echo ""
echo "2. Build the development APK:"
echo "   eas build --platform android --profile development --local"
echo ""
echo "   OR for cloud build (faster):"
echo "   eas build --platform android --profile development"
echo ""
echo "3. Once built, install the APK on your device"
echo ""
echo "4. Run the development server:"
echo "   npx expo start --dev-client"
echo ""
echo "Note: The first build will take 20-30 minutes"