#!/bin/bash

echo "Railway Fix Script"
echo "=================="
echo ""
echo "This script will help fix your Railway database connection."
echo ""
echo "1. First, install Railway CLI if you haven't:"
echo "   brew install railway"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Link to your project:"
echo "   railway link"
echo ""
echo "4. Run this command to see all your service variables:"
echo "   railway variables"
echo ""
echo "5. To set the DATABASE_URL properly, run:"
echo "   railway variables set DATABASE_URL=\$(railway variables get DATABASE_URL -s postgres)"
echo ""
echo "This will copy the actual database URL from your Postgres service to your backend service."