[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd korus-backend && npm ci --production=false"]

[phases.build]
cmds = ["cd korus-backend && npm run build"]

[start]
cmd = "cd korus-backend && npm run start:prod"