#!/bin/bash

echo "🔄 Quick Switch to Devnet"
echo "========================"
echo ""
echo "Update these configurations:"
echo ""
echo "1. Backend on Render:"
echo "   SOLANA_RPC_URL=https://api.devnet.solana.com"
echo "   GAME_ESCROW_PROGRAM_ID=9rLXaB3a8qeb55N119sC3mjK58LyPeXXnj8vEvm3EWFG"
echo ""
echo "2. Frontend config/environment.ts:"
echo "   solanaCluster: 'devnet'"
echo "   gameEscrowProgramId: '9rLXaB3a8qeb55N119sC3mjK58LyPeXXnj8vEvm3EWFG'"
echo ""
echo "3. Get free devnet SOL:"
echo "   https://faucet.solana.com"
echo ""
echo "✅ Ready to test in 5 minutes!"