[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules .cache && npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"

[variables]
NODE_ENV = "production"
PORT = "3000"