[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run migrate:deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
PORT = "3000"